version: '3.4'

services:
  termo:
    image: ${DOCKER_REGISTRY-}termo
    build:
      context: .
      dockerfile: Termo/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString:Server=db;Port=3306;Database=termoDB;Uid=root;Pwd=jelszavam;"
    ports:
      - "5050:80"
    volumes:
      - /Email/:/app/Email/
    depends_on:
      - "db"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jelszavam
      MYSQL_DATABASE: termoDB
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - "db"